### ISSUE TITLE
'http://' path in URI (amuse editing interface: make all links active)

### ISSUE THREAD

**Issue by rojenzaman** [melmothx/text-amuse-preprocessor#11]
When I insert wayback link to edit mode like: [[https://web.archive.org/web/20220504202253/https://amusewiki.org/special/index][wayback]]

amusewiki preview converts to this: [[https://web.archive.org/web/20220504202253/[[https://amusewiki.org/special/inde][amusewiki.org]]x][wayback]]

This means that preview mode forcefully converts "https". Is it error?

Note: this happens when "**Make all links active**" selection is marked.

**Comment by melmothx** [comment]
The problem is that the URL is parsed twice.
